name: System Pro Compiler Engine
on:
  workflow_dispatch:
    inputs:
      apk_path:
        description: 'Path to uploaded APK'
        required: true

jobs:
  decompile_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java & JADX
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-17-jdk
          wget https://github.com/skylot/jadx/releases/download/v1.5.0/jadx-1.5.0.zip
          unzip jadx-1.5.0.zip -d jadx_dir
          echo "$(pwd)/jadx_dir/bin" >> $GITHUB_PATH

      - name: Run Decompiler
        run: |
          mkdir -p decompiled_output
          # یہ کمانڈ APK کو مکمل ڈی کمپائل کرے گی
          jadx -d decompiled_output "${{ github.event.inputs.apk_path }}"

      - name: Save Results
        run: |
          git config --local user.email "systempro@ai.com"
          git config --local user.name "System Pro Bot"
          git add decompiled_output/
          git commit -m "Results for ${{ github.event.inputs.apk_path }}"
          git push
