name: System Pro Decompiler

on:
  repository_dispatch:
    types: [decompile-apk]

jobs:
  decompile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Install Jadx
        run: |
          sudo apt-get update
          wget https://github.com/skylot/jadx/releases/download/v1.4.7/jadx-1.4.7.zip
          unzip jadx-1.4.7.zip -d jadx
          echo "$(pwd)/jadx/bin" >> $GITHUB_PATH

      - name: Decode APK
        run: |
          echo "${{ github.event.client_payload.apk_base64 }}" | base64 -d > input.apk
          jadx input.apk -d out
          
      - name: Upload Decompiled Source
        uses: actions/upload-artifact@v4
        with:
          name: decompiled-source
          path: out/
