name: System Pro Compiler Engine
on:
  workflow_dispatch:
    inputs:
      apk_name:
        description: 'Name of the APK to decompile'
        required: true

jobs:
  decompile_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install JADX Decompiler
        run: |
          sudo apt-get update
          wget https://github.com/skylot/jadx/releases/download/v1.5.0/jadx-1.5.0.zip
          unzip jadx-1.5.0.zip -d jadx_bin
          echo "$(pwd)/jadx_bin/bin" >> $GITHUB_PATH

      - name: Decompile APK
        run: |
          # یہاں ہم فرض کر رہے ہیں کہ APK 'uploads' فولڈر میں ہے
          mkdir -p output/sources
          mkdir -p output/resources
          jadx -d output/ uploads/${{ github.event.inputs.apk_name }} || echo "Decompilation started..."

      - name: Commit and Push Results
        run: |
          git config --local user.email "systempro@bot.com"
          git config --local user.name "System Pro Engine"
          git add output/
          git commit -m "Decompiled results for ${{ github.event.inputs.apk_name }}"
          git push
