name: Decompile APK

on:
  workflow_dispatch:
    inputs:
      apk_name:
        description: 'APK file name'
        required: true

jobs:
  decompile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Install Apktool
        run: |
          wget https://raw.githubusercontent.com/iBotPeaches/Apktool/master/scripts/linux/apktool
          chmod +x apktool
          sudo mv apktool /usr/local/bin/

      - name: Download APK from repo
        run: |
          cp "${{ github.event.inputs.apk_name }}" ./input.apk

      - name: Decompile APK
        run: |
          apktool d input.apk -o decompiled/

      - name: Create result archive
        run: |
          cd decompiled && zip -r ../decompiled.zip ./*

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: decompiled-apk
          path: decompiled.zip
